name: GitHub CI

on:
  push:
    branches: [master]
  pull_request:
    types: [opened, synchronize, reopened, labeled]
  workflow_dispatch:

jobs:
  build:
    name: Build
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@main

      - name: Setup MSBuild
        uses: microsoft/setup-msbuild@main

      - name: Setup HDT
        shell: pwsh
        run: |
          Invoke-WebRequest (Invoke-WebRequest 'https://api.github.com/repos/HearthSim/Hearthstone-Deck-Tracker/releases' | ConvertFrom-Json)[0].assets.browser_download_url -OutFile HDT.zip
          Expand-Archive HDT.zip
          Rename-Item './HDT/Hearthstone Deck Tracker/Hearthstone Deck Tracker.exe' HearthstoneDeckTracker.exe

      - name: Build
        shell: pwsh
        run: |
          dotnet build PackTracker.sln

      - name: Upload
        uses: actions/upload-artifact@main
        if: github.ref == 'refs/heads/master' || startsWith(github.ref, 'refs/tags/')
        with:
          name: Artifact
          path: PackHistorian/bin/Debug
